# Generated by Django 4.2.3 on 2023-08-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30)),
                ('horsepower', models.CharField(max_length=30)),
                ('torque', models.CharField(max_length=25)),
                ('price', models.CharField(max_length=20)),
            ],
        ),
    ]
